name: lang_fe
description:
  A Flutter project showcasing supported Material 3 components, typography, color system and elevation.
  Supports different light/dark mode, color seed, and comparison to Material 2.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.3.0
  flutter: ^3.19.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.8
  sqflite:
  record:
  audioplayers:
  path: ^1.9.0
  path_provider: ^2.1.2
  archive:
  web_startup_analyzer:
    path: web_startup_analyzer

dev_dependencies:
  analysis_defaults:
    path: analysis_defaults
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
