name: lang_fe
description:
  Language Learning App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.3.0
  flutter: ^3.19.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.8
  sqflite:
  record:
  audioplayers:
  path: ^1.9.0
  path_provider: ^2.1.2
  intl: ^0.19.0
  archive:
  http:
  web_startup_analyzer:
    path: web_startup_analyzer
  firebase_core: ^2.27.2
  firebase_auth: ^4.18.0
  flutter_facebook_auth: ^6.1.1
  google_sign_in:
  firebase_messaging: ^14.7.21
  barcode_widget: ^2.0.4
  flutter_signin_button: ^2.0.0
  provider: ^6.1.2

dev_dependencies:
  analysis_defaults:
    path: analysis_defaults
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  xml: ^6.5.0

flutter:
  uses-material-design: true
