// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW0fy_sVYIBwwvEI3BvF7ORNcZavHdsGU',
    appId: '1:1017030229896:web:7981a4e2de29aca78c443d',
    messagingSenderId: '1017030229896',
    projectId: 'speaksharp-2decb',
    authDomain: 'speaksharp-2decb.firebaseapp.com',
    storageBucket: 'speaksharp-2decb.appspot.com',
    measurementId: 'G-X4W4PQ6M7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhi2W7E5_FCNDT2XMG_FPme4lw64yMjyQ',
    appId: '1:1017030229896:android:383ad3f94c6239aa8c443d',
    messagingSenderId: '1017030229896',
    projectId: 'speaksharp-2decb',
    storageBucket: 'speaksharp-2decb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3VL133qf_MFvFTozb0SdskinRg0KLRMg',
    appId: '1:1017030229896:ios:ad481cb67da090b48c443d',
    messagingSenderId: '1017030229896',
    projectId: 'speaksharp-2decb',
    storageBucket: 'speaksharp-2decb.appspot.com',
    iosBundleId: 'com.example.material3Demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3VL133qf_MFvFTozb0SdskinRg0KLRMg',
    appId: '1:1017030229896:ios:44162df9fd8e7c928c443d',
    messagingSenderId: '1017030229896',
    projectId: 'speaksharp-2decb',
    storageBucket: 'speaksharp-2decb.appspot.com',
    iosBundleId: 'com.example.material3Demo.RunnerTests',
  );
}
